Add reusable stale workflow
home-assistant/actions pull request #89
Opened 2023-06-15 09:43 UTC by agners

Add a stale GitHub action workflow which we can reuase in other repositories. This is meant as a non-mandatory default configuration.

It can be reused using the `uses` syntax in a job configuration, e.g.

```yaml
---
name: Stale

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: home-assistant/actions/.github/workflows/stale.yaml@master
```

2023-06-15 09:46 UTC, frenck approved these changes

2023-06-15 09:59 UTC, ludeeus commented on .github/workflows/stale.yaml
> +  workflow_call:
When using inputs for `workflow_call`, the `schedule` and `workflow_dispatch` triggers do not really make sense (I'm pretty sure it will also fail).

2023-06-15 09:59 UTC, ludeeus commented on .github/workflows/stale.yaml
> +      contents: write  # only for delete-branch option
```suggestion
```
I do not see that option in the configuration below, so this is not needed?

2023-06-15 09:59 UTC, ludeeus commented on .github/workflows/stale.yaml
> +          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security"
Should this be an input?

2023-06-15 09:59 UTC, ludeeus commented on .github/workflows/stale.yaml
> +          exempt-pr-labels: "pinned,no-stale,rfc,security"
Should this be an input?

2023-06-15 10:33 UTC, frenck commented on .github/workflows/stale.yaml
> +          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security"
What would be the case where we are going to use it?

2023-06-15 10:34 UTC, frenck requested changes
Left review comment on the recent change/suggestion made. Revoking approval.

2023-06-15 10:46 UTC, ludeeus commented on .github/workflows/stale.yaml
> +          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security"
<https://github.com/home-assistant/addons/blob/master/.github/workflows/stale.yml#L23>
<https://github.com/home-assistant/home-assistant.io/blob/current/.github/workflows/stale.yml#L23>
<https://github.com/home-assistant/tempio/blob/main/.github/workflows/stale.yml#L17>
<https://github.com/home-assistant/operating-system/blob/dev/.github/workflows/stale.yml#L30>
<https://github.com/home-assistant/frontend/blob/dev/.github/workflows/stale.yml>
We today already use different labels, so the use-case would be to keep current variations.
Another option is to extend this list with all used in the org.

2023-06-15 10:48 UTC, frenck commented on .github/workflows/stale.yaml
> +          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security"
> Another option is to extend this list with all used in the org.

I think that makes more sense, tbh (which was already done a bit).

2023-06-15 11:26 UTC, agners commented on .github/workflows/stale.yaml
> +          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security"
So the suggested default plus what comes as input, e.g.

```yaml
          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security,${{ inputs.additional-exempt-issue-labels }}"
```

2023-06-26 09:17 UTC, ludeeus approved these changes

2023-06-26 11:42 UTC, frenck approved these changes

2023-06-26 11:42 UTC, merged