Update README.md
home-assistant/actions pull request #97
Opened 2023-10-03 08:25 UTC by jwillemsen

Upgrade to actions/checkout v4

2023-10-03 08:28 UTC, frenck requested changes
Interesting, why doesn't dependabot pick this up?

2023-10-03 08:28 UTC, frenck commented on README.md
> +        - uses: "actions/checkout@v4"
Let's pin this stricly.

2023-10-03 08:30 UTC, jwillemsen commented on README.md
> +        - uses: "actions/checkout@v4"
This is in documentation, dependabot doesn't check that. v4 is strict enough, adding a minor will only result in much more dependabot updates.

2023-10-03 08:33 UTC, ludeeus commented on README.md
> +        - uses: "actions/checkout@v4"
How about making it invalid?
`- uses:  "actions/checkout@<look for the latest version at https://github.com/actions/checkout/releases>"`

2023-10-03 08:41 UTC, jwillemsen commented on README.md
> +        - uses: "actions/checkout@v4"
In my experience this will only confuse people, `actions/checkout` doesn't change often, having v4 in the text will allow people to quickly copy the example and integrate it in their repo

2023-10-03 08:48 UTC, frenck commented on README.md
> +        - uses: "actions/checkout@v4"
> This is in documentation

Goodmorning to myself 🤦

2023-10-06 09:53 UTC, frenck commented on README.md
> +        - uses: "actions/checkout@v4"
I'm ok with the current change.

2023-10-06 09:54 UTC, merged